### ISSUE TITLE
deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade

### ISSUE THREAD

**Issue by robogeek** [henrytseng/hostr#7]
I get this message when installing hostr

Hostr depends on a stale version of Mocha, that in turn depends on Jade.  The current Mocha version, 3.0.2, does not depend on Jade or Pug at all.

Updating the Mocha dependency would also solve this message:

```
deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
```

**Comment by henrytseng** [comment]
Good catch!  Should be resolved with 2.3.3
